name: tersedb
version: 0.1.0.0
github: "tersedb/tersedb-hs"
license: BSD-3-Clause
author: "Athan Clark"
maintainer: "athan.clark@gmail.com"
copyright: "2024 Athan Clark"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Entity Management System
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/tersedb/tersedb-hs#readme>

default-extensions:
  - DerivingVia
  - DataKinds
  - DeriveGeneric
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TypeFamilies

dependencies:
  - base >= 4.7 && < 5
  - aeson
  - base16-bytestring
  - bytestring
  - deriving-aeson
  - extra
  - hashable
  - lens
  - mtl
  - random
  - text
  - QuickCheck
  - quickcheck-instances
  - unordered-containers
  - utility-ht

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  # - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Wno-name-shadowing

library:
  source-dirs: src

executables:
  tersedb-hs:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tersedb

tests:
  tersedb-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tersedb
      - pretty-simple
      - sydtest
      - topograph
      - QuickCheck
